# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evolution_robot.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(300, 420, 151, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.logoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.logoLayout.setContentsMargins(0, 0, 0, 0)
        self.logoLayout.setObjectName("logoLayout")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 180, 181, 379))
        self.layoutWidget.setObjectName("layoutWidget")
        self.statsLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.statsLayout.setContentsMargins(0, 0, 0, 0)
        self.statsLayout.setObjectName("statsLayout")
        self.generation = QtWidgets.QLabel(self.layoutWidget)
        self.generation.setObjectName("generation")
        self.statsLayout.addWidget(self.generation)
        self.individual = QtWidgets.QLabel(self.layoutWidget)
        self.individual.setObjectName("individual")
        self.statsLayout.addWidget(self.individual)
        self.fitness = QtWidgets.QLabel(self.layoutWidget)
        self.fitness.setObjectName("fitness")
        self.statsLayout.addWidget(self.fitness)
        self.timer = QtWidgets.QLabel(self.layoutWidget)
        self.timer.setObjectName("timer")
        self.statsLayout.addWidget(self.timer)
        self.best_fitness = QtWidgets.QLabel(self.layoutWidget)
        self.best_fitness.setObjectName("best_fitness")
        self.statsLayout.addWidget(self.best_fitness)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 222, 144))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.buttonLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setObjectName("buttonLayout")
        self.trainButton = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.trainButton.setFont(font)
        self.trainButton.setObjectName("trainButton")
        self.buttonLayout.addWidget(self.trainButton)
        self.continueButton = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.continueButton.setFont(font)
        self.continueButton.setObjectName("continueButton")
        self.buttonLayout.addWidget(self.continueButton)
        self.generationButton = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.generationButton.setFont(font)
        self.generationButton.setObjectName("generationButton")
        self.buttonLayout.addWidget(self.generationButton)
        self.bestButton = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.bestButton.setFont(font)
        self.bestButton.setObjectName("bestButton")
        self.buttonLayout.addWidget(self.bestButton)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(210, 180, 81, 379))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.valueLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.valueLayout.setContentsMargins(0, 0, 0, 0)
        self.valueLayout.setObjectName("valueLayout")
        self.generation_value = QtWidgets.QLabel(self.layoutWidget_3)
        self.generation_value.setObjectName("generation_value")
        self.valueLayout.addWidget(self.generation_value)
        self.individual_value = QtWidgets.QLabel(self.layoutWidget_3)
        self.individual_value.setObjectName("individual_value")
        self.valueLayout.addWidget(self.individual_value)
        self.fitness_value = QtWidgets.QLabel(self.layoutWidget_3)
        self.fitness_value.setObjectName("fitness_value")
        self.valueLayout.addWidget(self.fitness_value)
        self.timer_value = QtWidgets.QLabel(self.layoutWidget_3)
        self.timer_value.setObjectName("timer_value")
        self.valueLayout.addWidget(self.timer_value)
        self.best_fitness_value = QtWidgets.QLabel(self.layoutWidget_3)
        self.best_fitness_value.setObjectName("best_fitness_value")
        self.valueLayout.addWidget(self.best_fitness_value)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(240, 20, 66, 144))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.percentageLayout = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.percentageLayout.setContentsMargins(0, 0, 0, 0)
        self.percentageLayout.setObjectName("percentageLayout")
        self.button_0 = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.button_0.setObjectName("button_0")
        self.percentageLayout.addWidget(self.button_0)
        self.button_25 = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.button_25.setObjectName("button_25")
        self.percentageLayout.addWidget(self.button_25)
        self.button_50 = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.button_50.setObjectName("button_50")
        self.percentageLayout.addWidget(self.button_50)
        self.button_75 = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.button_75.setObjectName("button_75")
        self.percentageLayout.addWidget(self.button_75)
        self.button_100 = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.button_100.setObjectName("button_100")
        self.percentageLayout.addWidget(self.button_100)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generation.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">CURRENT GENERATION: </span></p></body></html>"))
        self.individual.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">CURRENT INDIVIDUAL: </span></p></body></html>"))
        self.fitness.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">CURRENT FITNESS:</span></p></body></html>"))
        self.timer.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">TIMER: </span></p></body></html>"))
        self.best_fitness.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">BEST FITNESS: </span></p></body></html>"))
        self.trainButton.setText(_translate("MainWindow", "Start Training"))
        self.continueButton.setText(_translate("MainWindow", "Continue Training"))
        self.generationButton.setText(_translate("MainWindow", "Resume Generation"))
        self.bestButton.setText(_translate("MainWindow", "Test Best Chromosome"))
        self.generation_value.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.individual_value.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.fitness_value.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.timer_value.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.best_fitness_value.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.button_0.setText(_translate("MainWindow", "0%"))
        self.button_25.setText(_translate("MainWindow", "25%"))
        self.button_50.setText(_translate("MainWindow", "50%"))
        self.button_75.setText(_translate("MainWindow", "75%"))
        self.button_100.setText(_translate("MainWindow", "100%"))

import resources_rc
