# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train_robot.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

# Train Window
class Ui_TrainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(300, 420, 151, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.logoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.logoLayout.setContentsMargins(0, 0, 0, 0)
        self.logoLayout.setObjectName("logoLayout")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 180, 181, 379))
        self.layoutWidget.setObjectName("layoutWidget")
        self.statsLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.statsLayout.setContentsMargins(0, 0, 0, 0)
        self.statsLayout.setObjectName("statsLayout")
        self.generation = QtWidgets.QLabel(self.layoutWidget)
        self.generation.setObjectName("generation")
        self.statsLayout.addWidget(self.generation)
        self.individual = QtWidgets.QLabel(self.layoutWidget)
        self.individual.setObjectName("individual")
        self.statsLayout.addWidget(self.individual)
        self.timer = QtWidgets.QLabel(self.layoutWidget)
        self.timer.setObjectName("timer")
        self.statsLayout.addWidget(self.timer)
        self.best_fitness = QtWidgets.QLabel(self.layoutWidget)
        self.best_fitness.setObjectName("best_fitness")
        self.statsLayout.addWidget(self.best_fitness)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 222, 144))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.buttonLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setObjectName("buttonLayout")
        self.trainButton = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.trainButton.setFont(font)
        self.trainButton.setObjectName("trainButton")
        self.buttonLayout.addWidget(self.trainButton)
        self.generationButton = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.generationButton.setFont(font)
        self.generationButton.setObjectName("generationButton")
        self.buttonLayout.addWidget(self.generationButton)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(210, 180, 81, 379))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.valueLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.valueLayout.setContentsMargins(0, 0, 0, 0)
        self.valueLayout.setObjectName("valueLayout")
        self.generation_value = QtWidgets.QLabel(self.layoutWidget_3)
        self.generation_value.setObjectName("generation_value")
        self.valueLayout.addWidget(self.generation_value)
        self.individual_value = QtWidgets.QLabel(self.layoutWidget_3)
        self.individual_value.setObjectName("individual_value")
        self.valueLayout.addWidget(self.individual_value)
        self.timer_value = QtWidgets.QLabel(self.layoutWidget_3)
        self.timer_value.setObjectName("timer_value")
        self.valueLayout.addWidget(self.timer_value)
        self.best_fitness_value = QtWidgets.QLabel(self.layoutWidget_3)
        self.best_fitness_value.setObjectName("best_fitness_value")
        self.valueLayout.addWidget(self.best_fitness_value)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(240, 20, 228, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.generationLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.generationLayout.setContentsMargins(0, 0, 0, 0)
        self.generationLayout.setObjectName("generationLayout")
        self.out_of_generation = QtWidgets.QLabel(self.gridLayoutWidget)
        self.out_of_generation.setObjectName("out_of_generation")
        self.generationLayout.addWidget(self.out_of_generation, 0, 1, 1, 1)
        self.input_generation = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.input_generation.setObjectName("input_generation")
        self.generationLayout.addWidget(self.input_generation, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.generationLayout.addWidget(self.label, 1, 0, 1, 1)
        self.last_generation = QtWidgets.QLabel(self.gridLayoutWidget)
        self.last_generation.setObjectName("last_generation")
        self.generationLayout.addWidget(self.last_generation, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generation.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">CURRENT GENERATION: </span></p></body></html>"))
        self.individual.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">CURRENT INDIVIDUAL: </span></p></body></html>"))
        self.timer.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">CURRENT TIMER: </span></p></body></html>"))
        self.best_fitness.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">BEST FITNESS: </span></p></body></html>"))
        self.trainButton.setText(_translate("MainWindow", "Start Training"))
        self.generationButton.setText(_translate("MainWindow", "Resume Generation"))
        self.generation_value.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.individual_value.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.timer_value.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.best_fitness_value.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.out_of_generation.setText(_translate("MainWindow", "/ 0"))
        self.label.setText(_translate("MainWindow", "The last generation was: "))
        self.last_generation.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0</p></body></html>"))

    
# Test window    
class Ui_TestWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 279)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(310, 110, 151, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.logoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.logoLayout.setContentsMargins(0, 0, 0, 0)
        self.logoLayout.setObjectName("logoLayout")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 222, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.buttonLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setObjectName("buttonLayout")
        self.bestButton = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.bestButton.setFont(font)
        self.bestButton.setObjectName("bestButton")
        self.buttonLayout.addWidget(self.bestButton)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(240, 20, 221, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.bestLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.bestLayout.setContentsMargins(0, 0, 0, 0)
        self.bestLayout.setObjectName("bestLayout")
        self.input_generation_2 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.input_generation_2.setObjectName("input_generation_2")
        self.bestLayout.addWidget(self.input_generation_2, 2, 0, 1, 1)
        self.out_of_generation_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.out_of_generation_2.setObjectName("out_of_generation_2")
        self.bestLayout.addWidget(self.out_of_generation_2, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.bestLayout.addWidget(self.label_2, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bestButton.setText(_translate("MainWindow", "Test Best Chromosome"))
        self.out_of_generation_2.setText(_translate("MainWindow", "/ 0"))
        self.label_2.setText(_translate("MainWindow", "Select the generation to play "))

import resources_rc
